language: rust

matrix:
  include:
    - os: windows
      rust: stable
      env:
        - DEPLOY=1

    - os: windows
      rust: beta

    - os: windows
      rust: nightly

    - os: linux
      rust: stable
      env:
        - DEPLOY=1

    - os: linux
      rust: beta

    - os: linux
      rust: nightly

    - os: osx
      rust: stable
      env:
        - DEPLOY=1

    - os: osx
      rust: beta

    - os: osx
      rust: nightly
      
  allow_failures:
    - rust: nightly

env: 
  global:
    - RUST_BACKTRACE=1

script:
  - cargo test

before_deploy:
  - if [[ "$TRAVIS_OS_NAME" = "windows" ]]; then choco install zip; fi
  - cargo build --release
  - mkdir -p target/release/laegluin.cml
  - cp -r cmlc/package.json cmlc/language-configuration.json cmlc/grammars target/release/laegluin.cml
  - cd target/release
  - zip -r $TRAVIS_TAG-$TRAVIS_OS_NAME.zip simulator cmlc simulator.exe cmlc.exe laegluin.cml
  - cd ../..

deploy:
  provider: releases
  api_key:
    secure: B+FG2jpKHs7DU6DiVlOC9vEjEobPijwdbcXA0mK72TQ3SXMEXyjvDGdfPx+Zd4mj+u6SfIiUHIUdw4HdxVXnsJ4Cj/PpeD4rjoWnx1vmuXQULkvwBjrAELoPobaQthVm+Ntz1emzxXOJ5ZiIfJxAj2icxWhfxgdLTpKJZeHGPf9F7JHmP5GWAGJ6DquSgri3SARRa552HlV1NscuiBgSlgSTlPPaKxz9lzM70IoyXcP523oOoJEJgV/ONGdLR5qTCPyzt9/pDU3+r1naAJqRD93N+8kieY+xNBxicisgO7Sdbk9bxKc13GgVfMcoy2sZ5kucjjzCvEbUNV2t5cSY9rM/Ebqdg0xGi6X1J4J0UnfPTxa6C9mdQ0WrJh8zeG26iggObrtIoB1giR5qM/2JkUgH3R0RPPXs4mo+Q9voNpP5SrUcWywswvJ44uVBqHk1KPBPbU2pMXptEZsdyWx9aFlzLmm1kS6xo+AGGr3T6Fdz7KZqoLR/nnTa+ukiPZZCjdJFl1fKi7Tb16aR7E2EM9t3gy9VlW64/UNYPoiHqvIcLbOWIRHMjB00k7xPqxSI9MH0uYFQnL0TAcVA3agjbsubA/mfvNzICpI6TNodEtW5bHzfXvmVOTCRHVI6B3maGy4lYo420aQMVCOGD3b987fDn5kouO7zSCpOSvtpA9A=
  on:
    tags: true
  condition: $DEPLOY = 1
  skip_cleanup: true
  file_glob: true
  file: target/release/*.zip
